name: rlog
description: An easy-to-use logging library with some presets, like Rotation, Console, Multi.
version: 0.0.2
homepage: https://github.com/Ronbb/rlog
repository: https://github.com/Ronbb/rlog.git

environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  path: ^1.8.0
