name: rlog
description: An easy-to-use logging library with some presets.
version: 0.0.1+1
homepage: https://github.com/Ronbb/rlog
repository: https://github.com/Ronbb/rlog.git

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  path: ^1.8.2
